version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  apache:
    image: httpd

  static:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    restart: always